# Generated by Django 2.0 on 2024-03-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yhm', models.CharField(max_length=40)),
                ('mm', models.CharField(max_length=40)),
                ('xm', models.CharField(max_length=40)),
            ],
        ),
    ]
