# Generated by Django 2.0 on 2024-03-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jiaoshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yhm', models.CharField(max_length=40)),
                ('mm', models.CharField(max_length=40)),
                ('xm', models.CharField(max_length=40)),
                ('lxdh', models.CharField(max_length=40)),
                ('zc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='jsjy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqh', models.CharField(max_length=40)),
                ('bt', models.CharField(max_length=40)),
                ('nr', models.CharField(max_length=40)),
                ('js', models.CharField(max_length=40)),
                ('sqrq', models.CharField(max_length=40)),
                ('sjd', models.CharField(max_length=40)),
                ('sqsj', models.CharField(max_length=40)),
                ('sqzt', models.CharField(max_length=40)),
                ('yh', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='jsxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsmc', models.CharField(max_length=40)),
                ('wz', models.CharField(max_length=40)),
                ('bz', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='kecheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcmc', models.CharField(max_length=40)),
                ('rkjs', models.CharField(max_length=40)),
                ('sm', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='qiandao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sksj', models.CharField(max_length=40)),
                ('xs', models.CharField(max_length=40)),
                ('zt', models.CharField(max_length=40)),
                ('rq', models.CharField(max_length=40)),
                ('qdsj', models.CharField(max_length=40)),
                ('qtsj', models.CharField(max_length=40)),
                ('kc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='sjd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjd', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='sksj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsh', models.CharField(max_length=40)),
                ('xq', models.CharField(max_length=40)),
                ('sjd', models.CharField(max_length=40)),
                ('kc', models.CharField(max_length=40)),
                ('js', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='xingqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xq', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='xuesheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yhm', models.CharField(max_length=40)),
                ('mm', models.CharField(max_length=40)),
                ('xm', models.CharField(max_length=40)),
                ('lxdh', models.CharField(max_length=40)),
                ('zy', models.CharField(max_length=40)),
            ],
        ),
    ]
